### ISSUE TITLE
Resetting alpha value on color change

### ISSUE THREAD

**Issue by Varshamathukumalli** [zefoy/ngx-color-picker#192]
Hi,

We have an issue with alpha value. We are providing inputs as below:

- input color: rgba(0,0,0,0)

- output format: hex

- cpAlphaChannel: disabled

and we have hidden the slider to change alpha value.
In this case though user changes the color, the selected color div won't be displayed with the color chosen by user because initially alpha level is set as "0".
Is there any way to rest the alpha value whenever the color is modified.

The below url explains the issue. Initially color is transparent, now changing the color won't change. the selected color div element. (Note: Alpha slider bar won't be visible to end user)

https://stackblitz.com/edit/github-5uzpa1?file=src%2Fapp%2Fapp.component.html

**Comment by sconix** [comment]
This sounds something that I am not sure if the picker should even handle, but I guess specially since you have set the alpha channel to disabled it would not hurt for the color picker to override the alpha. At least I think it makes sense so I will add a fix for this.

**Comment by sconix** [comment]
This should be fixed in the next release. When output format is set to hex i.e. none alpha capable then the alpha from the input color is ignored.

**Comment by Varshamathukumalli** [comment]
@sconix , is the above fix released in 8.1.0 or it is going to be released in next build. Becuase this is not reflecting in the above mentioned url.

**Comment by sconix** [comment]
Yes this was fixed in 8.1.0.

**Comment by Varshamathukumalli** [comment]
But in the above provided url, the issue is not resolved even after upgrading to latest. Do we need to set/call something in addition to that. can you please verify and confirm?

**Comment by sconix** [comment]
In you example there are code errors. You are passing undefined as cpOutputFormat and cpAlphaChannel. Strings need to have '' around them or Angular passes variable named hex/disabled.
