### ISSUE TITLE
Disable hex input auto completing

### ISSUE THREAD

**Issue by sumitsheokand** [zefoy/ngx-color-picker#377]
Currently, when typing the first three characters into the hex input field, it automatically expands.

Example:

If you enter #def, the input control updates the value to #ddeeff

![Image](https://github.com/user-attachments/assets/4b014ed2-1f5e-4ee1-a041-ad62728f2ead)

**Comment by sconix** [comment]
We plan to fix this soonish at the latest when Angualr 20 is out, but most likely already earlier. In the meantime PR's are accepted.

**Comment by sumitsheokand** [comment]
Hi @sconix, just checking in — has the above issue been resolved, or is it still in progress and expected to take some more time?

**Comment by sconix** [comment]
Il try to make the new release with the fix this week.

**Comment by sconix** [comment]
It is fixed in latest release, the whole autofill code was removes

**Comment by sumitsheokand** [comment]
@sconix I tested the code after upgrading to the latest version, but the issue still persists. When a three-digit value is entered in the event, it gets converted into six digits. This conversion should be properly handled in the (colorPickerChange)="setColor($event)" implementation.

<img width="1889" height="646" alt="Image" src="https://github.com/user-attachments/assets/66de15e0-80b4-4db3-8f3f-0d7f10a8ff35" />
